      *>------------------------------------------------------------------------------
      *> <auto-generated>
      *>     This code was generated by a tool.
      *>
      *>     Changes to this file may cause incorrect behavior and will be lost if
      *>     the code is regenerated.
      *> </auto-generated>
      *>------------------------------------------------------------------------------
       class-id batsweb.summaryrunners is partial public.
                 
       working-storage section.

      *>> <summary>
      *>> form1 control.
      *>> </summary>
      *>> <remarks>
      *>> Auto-generated field.
      *>> To modify move field declaration from designer file to code-behind file.
      *>> </remarks>
       01 form1 type System.Web.UI.HtmlControls.HtmlForm property.

       end class.
